// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `cpp_library/src/typhon.h`.
/// Regenerate bindings with `dart run ffigen --config ffigen_typhon.yaml`.
///
class TyphonBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TyphonBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TyphonBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// __BEGIN__CPP__EXPORTS__
  void passPlatformSpecificViewPointer(
    ffi.Pointer<ffi.Void> view,
  ) {
    return _passPlatformSpecificViewPointer(
      view,
    );
  }

  late final _passPlatformSpecificViewPointerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'passPlatformSpecificViewPointer');
  late final _passPlatformSpecificViewPointer =
      _passPlatformSpecificViewPointerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void setPlatformSpecificWindowSizeAndPos(
    double x,
    double y,
    double width,
    double height,
  ) {
    return _setPlatformSpecificWindowSizeAndPos(
      x,
      y,
      width,
      height,
    );
  }

  late final _setPlatformSpecificWindowSizeAndPosPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Double, ffi.Double, ffi.Double,
              ffi.Double)>>('setPlatformSpecificWindowSizeAndPos');
  late final _setPlatformSpecificWindowSizeAndPos =
      _setPlatformSpecificWindowSizeAndPosPtr
          .asFunction<void Function(double, double, double, double)>();

  ffi.Pointer<ffi.Void> getPlatformSpecificPointer() {
    return _getPlatformSpecificPointer();
  }

  late final _getPlatformSpecificPointerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
          'getPlatformSpecificPointer');
  late final _getPlatformSpecificPointer = _getPlatformSpecificPointerPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  bool initializeCppLibrary() {
    return _initializeCppLibrary();
  }

  late final _initializeCppLibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('initializeCppLibrary');
  late final _initializeCppLibrary =
      _initializeCppLibraryPtr.asFunction<bool Function()>();

  void onMouseMove(
    double positionX,
    double positionY,
  ) {
    return _onMouseMove(
      positionX,
      positionY,
    );
  }

  late final _onMouseMovePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Double, ffi.Double)>>(
          'onMouseMove');
  late final _onMouseMove =
      _onMouseMovePtr.asFunction<void Function(double, double)>();

  void onKeyboardKeyDown(
    int input,
  ) {
    return _onKeyboardKeyDown(
      input,
    );
  }

  late final _onKeyboardKeyDownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'onKeyboardKeyDown');
  late final _onKeyboardKeyDown =
      _onKeyboardKeyDownPtr.asFunction<void Function(int)>();

  void onKeyboardKeyUp(
    int input,
  ) {
    return _onKeyboardKeyUp(
      input,
    );
  }

  late final _onKeyboardKeyUpPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'onKeyboardKeyUp');
  late final _onKeyboardKeyUp =
      _onKeyboardKeyUpPtr.asFunction<void Function(int)>();

  void onUpdateCall(
    double dt,
  ) {
    return _onUpdateCall(
      dt,
    );
  }

  late final _onUpdateCallPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Double)>>(
          'onUpdateCall');
  late final _onUpdateCall =
      _onUpdateCallPtr.asFunction<void Function(double)>();

  void onRenderCall(
    double dt,
  ) {
    return _onRenderCall(
      dt,
    );
  }

  late final _onRenderCallPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Double)>>(
          'onRenderCall');
  late final _onRenderCall =
      _onRenderCallPtr.asFunction<void Function(double)>();

  void passProjectPath(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _passProjectPath(
      path,
    );
  }

  late final _passProjectPathPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'passProjectPath');
  late final _passProjectPath =
      _passProjectPathPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void attachEnqueueRender(
    EnqueueObjectRender func,
  ) {
    return _attachEnqueueRender(
      func,
    );
  }

  late final _attachEnqueueRenderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(EnqueueObjectRender)>>(
          'attachEnqueueRender');
  late final _attachEnqueueRender =
      _attachEnqueueRenderPtr.asFunction<void Function(EnqueueObjectRender)>();

  void attachOnChildrenChanged(
    OnChildrenChangedFunc func,
  ) {
    return _attachOnChildrenChanged(
      func,
    );
  }

  late final _attachOnChildrenChangedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OnChildrenChangedFunc)>>(
          'attachOnChildrenChanged');
  late final _attachOnChildrenChanged = _attachOnChildrenChangedPtr
      .asFunction<void Function(OnChildrenChangedFunc)>();

  void unloadLibrary() {
    return _unloadLibrary();
  }

  late final _unloadLibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('unloadLibrary');
  late final _unloadLibrary = _unloadLibraryPtr.asFunction<void Function()>();

  void createObjectFromClassID(
    int classID,
  ) {
    return _createObjectFromClassID(
      classID,
    );
  }

  late final _createObjectFromClassIDPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'createObjectFromClassID');
  late final _createObjectFromClassID =
      _createObjectFromClassIDPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> getInstantiableClasses() {
    return _getInstantiableClasses();
  }

  late final _getInstantiableClassesPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getInstantiableClasses');
  late final _getInstantiableClasses =
      _getInstantiableClassesPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  bool isEngineInitialized() {
    return _isEngineInitialized();
  }

  late final _isEngineInitializedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function()>>('isEngineInitialized');
  late final _isEngineInitialized =
      _isEngineInitializedPtr.asFunction<bool Function()>();

  AliveObjectsArray getAliveParentlessObjects() {
    return _getAliveParentlessObjects();
  }

  late final _getAliveParentlessObjectsPtr =
      _lookup<ffi.NativeFunction<AliveObjectsArray Function()>>(
          'getAliveParentlessObjects');
  late final _getAliveParentlessObjects =
      _getAliveParentlessObjectsPtr.asFunction<AliveObjectsArray Function()>();

  ffi.Pointer<ffi.Char> getObjectNameByID(
    int id,
  ) {
    return _getObjectNameByID(
      id,
    );
  }

  late final _getObjectNameByIDPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int64)>>(
          'getObjectNameByID');
  late final _getObjectNameByID =
      _getObjectNameByIDPtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  void removeObjectByID(
    int id,
  ) {
    return _removeObjectByID(
      id,
    );
  }

  late final _removeObjectByIDPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'removeObjectByID');
  late final _removeObjectByID =
      _removeObjectByIDPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> getObjectSerializationByID(
    int id,
  ) {
    return _getObjectSerializationByID(
      id,
    );
  }

  late final _getObjectSerializationByIDPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int64)>>(
          'getObjectSerializationByID');
  late final _getObjectSerializationByID = _getObjectSerializationByIDPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> getObjectInspectorUIByID(
    int id,
  ) {
    return _getObjectInspectorUIByID(
      id,
    );
  }

  late final _getObjectInspectorUIByIDPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int64)>>(
          'getObjectInspectorUIByID');
  late final _getObjectInspectorUIByID = _getObjectInspectorUIByIDPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> getObjectChildTree(
    int id,
  ) {
    return _getObjectChildTree(
      id,
    );
  }

  late final _getObjectChildTreePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int64)>>(
          'getObjectChildTree');
  late final _getObjectChildTree =
      _getObjectChildTreePtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  bool setObjectParent(
    int objectID,
    int parentID,
  ) {
    return _setObjectParent(
      objectID,
      parentID,
    );
  }

  late final _setObjectParentPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Int64)>>(
          'setObjectParent');
  late final _setObjectParent =
      _setObjectParentPtr.asFunction<bool Function(int, int)>();

  bool setObjectName(
    int objectID,
    ffi.Pointer<ffi.Char> str,
    int size,
  ) {
    return _setObjectName(
      objectID,
      str,
      size,
    );
  }

  late final _setObjectNamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Int64)>>('setObjectName');
  late final _setObjectName = _setObjectNamePtr
      .asFunction<bool Function(int, ffi.Pointer<ffi.Char>, int)>();

  bool removeObjectFromParent(
    int objectID,
  ) {
    return _removeObjectFromParent(
      objectID,
    );
  }

  late final _removeObjectFromParentPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>(
          'removeObjectFromParent');
  late final _removeObjectFromParent =
      _removeObjectFromParentPtr.asFunction<bool Function(int)>();

  ffi.Pointer<ffi.Char> getContextMenuForFilePath(
    ffi.Pointer<ffi.Char> filePath,
    int size,
  ) {
    return _getContextMenuForFilePath(
      filePath,
      size,
    );
  }

  late final _getContextMenuForFilePathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>, ffi.Int64)>>('getContextMenuForFilePath');
  late final _getContextMenuForFilePath = _getContextMenuForFilePathPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, int)>();

  void loadModelFromPath(
    ffi.Pointer<ffi.Char> filePath,
    int size,
  ) {
    return _loadModelFromPath(
      filePath,
      size,
    );
  }

  late final _loadModelFromPathPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Int64)>>(
      'loadModelFromPath');
  late final _loadModelFromPath = _loadModelFromPathPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();
}

typedef EnqueueObjectRender = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            ffi.Double,
            ffi.Double,
            ffi.Int64,
            ffi.Int64,
            ffi.Int64,
            ffi.Int64,
            ffi.Double,
            ffi.Double,
            ffi.Double,
            ffi.Double)>>;
typedef OnChildrenChangedFunc
    = ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>;

final class AliveObjectsArray extends ffi.Struct {
  external ffi.Pointer<ffi.Int64> array;

  @ffi.Int64()
  external int size;
}
